<a href="https://colab.research.google.com/github/git-siddhesh/MachineLearning_ES654_2022/blob/main/implement_argmin_successful.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
def find_min_idx(arr ):
    # print(arr,"\n")
    if arr.ndim == 1:
        min_idx = 0
        min_val = arr[0]
        for i in range(1, len(arr)):
            if min_val > arr[i]:
                min_val = arr[i]
                min_idx = i
        return min_idx
    else:
        ans1 = [None]*arr.shape[1]
        for k in range(arr.shape[1]):
            ans1[k] = find_min_idx(arr[:,k])
        return ans1
def argmin(arr, axis = None):
    arr = np.array(arr)
    if axis == None:
        min_idx = 0
        arr2 = arr.flatten()
        min_val = arr2[0]
        for i in range(1, len(arr2)):
            if min_val > arr2[i]:
                min_val = arr2[i]
                min_idx = i
        return min_idx
    elif axis == 1:
        ans = [None]*arr.shape[0]
        for row in range(arr.shape[0]):
            ans[row] = find_min_idx(arr[row,:])
        return ans

    else:
        ans = [None]*arr.shape[1]
        for col in range(arr.shape[1]):
            ans[col] = find_min_idx(arr[:,col])
        return ans

array = np.array([
                    [ 
                        [
                            [1,2],
                            [3,2]
                        ],     # row1
                        [   
                            [2,1],
                            [3,2]
                        ],     # row2
                        [  
                            [3,1],
                            [1,2]
                        ]      # row3
                    ],
                    [   
                        [
                            [2,1],
                            [2,2]
                        ],     # row1
                        [   
                            [1,2],
                            [3,2]
                        ],     # row2
                        [   
                            [1,3],
                            [3,2]
                        ]      # row3
                    ]
                ])       

print("ANSWER: ",argmin(array,axis = 0))
print() 
print("ANSWER: ",argmin(array,axis = 1)) 

print("Actual answer: ")
print(np.argmin(array,axis = 0),end= "\n\n")
print(np.argmin(array, axis = 1))

print("SHAPE: ", array.shape)

ANSWER:  [[[0, 1], [1, 0]], [[1, 0], [0, 0]], [[1, 0], [0, 0]]]

ANSWER:  [[[0, 1], [2, 0]], [[1, 0], [0, 0]]]
Actual answer: 
[[[0 1]
  [1 0]]

 [[1 0]
  [0 0]]

 [[1 0]
  [0 0]]]

[[[0 1]
  [2 0]]

 [[1 0]
  [0 0]]]
SHAPE:  (2, 3, 2, 2)
